# app.py — Streamlit one-page frontend (Python-only)
# Run:  streamlit run app.py
# Notes:
# - Set API_BASE to your FastAPI backend base (e.g., http://localhost:8000).
# - Uses /chat for natural LLM replies, /explain for relationship summaries.
# - If API isn't reachable, it falls back to safe mock data so you can demo the UI.

import os
import json
import time
from typing import Dict, Any, List, Optional

import requests
import streamlit as st

# -----------------------------
# Config & Theme
# -----------------------------
st.set_page_config(page_title="OFSAA-BOT", page_icon="🛡️", layout="wide")
API_BASE = os.getenv("API_BASE", "http://localhost:8000")

# Minimal CSS polish (rounded cards, subtle shadows, compact tables)
st.markdown(
    """
    <style>
      .stChatFloatingInputContainer { border-top: 1px solid rgba(49,51,63,0.2) }
      .app-header { display:flex; align-items:center; gap:.6rem; }
      .badge { display:inline-block; padding:.15rem .45rem; border-radius:999px; font-size:0.72rem; background:#EEF2FF; color:#3730A3; border:1px solid #C7D2FE; }
      .pill { padding:.35rem .6rem; border:1px solid rgba(0,0,0,.08); border-radius:999px; margin-right:.4rem; cursor:pointer; }
      .pill:hover { background:rgba(0,0,0,.04); }
      .card { background:white; border-radius:16px; padding:1rem; box-shadow: 0 1px 2px rgba(0,0,0,.06), 0 8px 24px rgba(0,0,0,.06); }
      .sql { border:1px solid rgba(0,0,0,.08); }
      .footer { color:#6b7280; font-size:.85rem; }
      .small { font-size:.85rem; }
      .tight-table table { font-size: 0.92rem; }
    </style>
    """,
    unsafe_allow_html=True,
)

# -----------------------------
# Helpers
# -----------------------------
def _api_post(path: str, payload: Dict[str, Any], timeout: int = 30) -> Optional[Dict[str, Any]]:
    try:
        r = requests.post(f"{API_BASE}{path}", json=payload, timeout=timeout)
        r.raise_for_status()
        return r.json()
    except Exception:
        return None

def call_chat(question: str, schema: str, tone: str) -> Dict[str, Any]:
    """
    Calls /chat for LLM-generated, human-like replies.
    Falls back to deterministic mock aligned to demo content.
    """
    payload = {"message": question, "schema": schema, "tone": tone}
    data = _api_post("/chat", payload)
    if data:
        return data

    # Mock fallback: reply + tables + sql_snippets
    mock_schema = schema or "OFSAAFCCM"
    mock_tables = [
        {"OWNER": mock_schema, "TABLE_NAME": "TXN_ALERTS", "COMMENTS": "Alerts generated by batch (daily)"},
        {"OWNER": mock_schema, "TABLE_NAME": "ALERT_HISTORY", "COMMENTS": "Alert timeline and status transitions"},
        {"OWNER": mock_schema, "TABLE_NAME": "STG_PARTY_MASTER", "COMMENTS": "Staging for party/customer info"},
    ]
    mock_sql = [
        "SELECT owner, table_name, comments\n"
        "FROM all_tab_comments\n"
        "WHERE owner=:owner AND (LOWER(table_name) LIKE LOWER(:kw) OR LOWER(comments) LIKE LOWER(:kw2))\n"
        "ORDER BY table_name"
    ]
    reply = (
        f"(Mock) Tables matching your query in {mock_schema}. I found {len(mock_tables)} rows.\n\n"
        "• TXN_ALERTS — Alerts generated by batch (daily)\n"
        "• ALERT_HISTORY — Alert timeline and status transitions\n"
        "• STG_PARTY_MASTER — Staging for party/customer info\n\n"
        "I can narrow this down or switch to columns/keys/partitions."
    )
    return {"reply": reply, "tables": mock_tables, "sql_snippets": mock_sql}

def call_explain(schema: str, keyword: str) -> Dict[str, Any]:
    """
    Calls /explain for keyword-based table discovery + relationship graph summary.
    Falls back to mock graph consistent with demo tables.
    """
    payload = {"schema": schema, "keyword": keyword}
    data = _api_post("/explain", payload)
    if data:
        # unify shape to match chat renderer (answer/reply + tables + sql)
        return {
            "reply": data.get("summary"),
            "tables": data.get("tables"),
            "sql_snippets": data.get("sql_snippets"),
        }

    mock_schema = schema or "OFSAAFCCM"
    mock_tables = [
        {"OWNER": mock_schema, "TABLE_NAME": "TXN_ALERTS", "COMMENTS": "Alerts generated by batch (daily)"},
        {"OWNER": mock_schema, "TABLE_NAME": "ALERT_HISTORY", "COMMENTS": "Alert timeline and status transitions"},
        {"OWNER": mock_schema, "TABLE_NAME": "STG_PARTY_MASTER", "COMMENTS": "Staging for party/customer info"},
    ]
    mock_sql = [
        "/* find tables */ SELECT owner, table_name, comments FROM all_tab_comments WHERE owner=:owner AND UPPER(table_name) LIKE :kw",
        "/* fk edges */ SELECT ... FROM all_constraints ...",
        "/* pk cols */ SELECT ... FROM all_constraints ...",
    ]
    summary = (
        f"(Mock) I found {len(mock_tables)} rows related to ALERT in {mock_schema}. Here’s how they connect:\n"
        "• ALERT_HISTORY → TXN_ALERTS via (ALERT_ID) → (ALERT_ID)\n"
        "• TXN_ALERTS → STG_PARTY_MASTER via (PARTY_ID) → (PARTY_ID)\n\n"
        "**Table notes:**\n"
        "• TXN_ALERTS — Alerts generated by batch (daily)\n"
        "• ALERT_HISTORY — Alert timeline and status transitions\n"
        "• STG_PARTY_MASTER — Staging for party/customer info"
    )
    return {"reply": summary, "tables": mock_tables, "sql_snippets": mock_sql}

def typing_write(text: str, delay: float = 0.0):
    """
    Simple typing effect; set delay>0 for demo flair.
    """
    if not delay:
        st.markdown(text)
        return
    ph = st.empty()
    buf = ""
    for ch in text:
        buf += ch
        ph.markdown(buf)
        time.sleep(delay)

def message(role: str, content: Any, typing_delay: float = 0.0):
    with st.chat_message("user" if role == "user" else "assistant"):
        if role == "user":
            st.write(content)
        else:
            # Prefer LLM "reply"; fallback to deterministic "answer"
            text = content.get("reply") or content.get("answer") or ""
            typing_write(text, delay=typing_delay)

            # Results Tabs
            tabs = st.tabs(["Results", "SQL Used", "Notes"])
            with tabs[0]:
                if content.get("tables"):
                    with st.container():
                        st.markdown("<div class='card tight-table'>", unsafe_allow_html=True)
                        st.dataframe(content["tables"], use_container_width=True)
                        st.markdown("</div>", unsafe_allow_html=True)
                else:
                    st.info("No rows to display.")
            with tabs[1]:
                if content.get("sql_snippets"):
                    for s in content["sql_snippets"]:
                        st.code(s, language="sql")
                else:
                    st.caption("No SQL captured.")
            with tabs[2]:
                st.caption("Read-only • Dictionary views only • Parametrised queries • Audit friendly")

# -----------------------------
# Sidebar & Header
# -----------------------------
with st.sidebar:
    st.markdown("<div class='app-header'>🛡️ <strong>OFSAA-BOT</strong></div>", unsafe_allow_html=True)
    schema = st.text_input("Schema (allow-list enforced)", value="OFSAAFCCM")
    tone = st.radio("Tone", ["friendly", "formal"], index=0, horizontal=True)
    st.markdown("<span class='badge'>Internal Demo</span>", unsafe_allow_html=True)
    st.divider()
    st.subheader("Quick Prompts")

    cols = st.columns(2)
    with cols[0]:
        if st.button("List KYC tables", use_container_width=True):
            st.session_state.setdefault("pending_prompt", {"type": "chat", "q": "list tables for kyc"})
    with cols[1]:
        if st.button("Describe PARTY_MASTER", use_container_width=True):
            st.session_state.setdefault("pending_prompt", {"type": "chat", "q": "describe table STG_PARTY_MASTER"})
    cols = st.columns(2)
    with cols[0]:
        if st.button("Keys TXN_ALERTS", use_container_width=True):
            st.session_state.setdefault("pending_prompt", {"type": "chat", "q": "keys of table TXN_ALERTS"})
    with cols[1]:
        if st.button("Partitions ALERT_HISTORY", use_container_width=True):
            st.session_state.setdefault("pending_prompt", {"type": "chat", "q": "partition info of table ALERT_HISTORY"})
    st.divider()
    if st.button("Explain ALERT tables (relations)", use_container_width=True):
        st.session_state.setdefault("pending_prompt", {"type": "explain", "kw": "ALERT"})
    st.divider()
    st.caption("Set API_BASE env to target your backend. Defaults to http://localhost:8000")

st.markdown(
    """
    <div class='card'>
      <div class='app-header'>
        <h2 style='margin:0'>OFSAA-BOT</h2>
        <span class='badge'>Metadata-only</span>
      </div>
      <p class='small'>Ask questions about tables, columns, keys, and partitions. The app never queries business data—only Oracle dictionary metadata.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

# -----------------------------
# Session State
# -----------------------------
if "history" not in st.session_state:
    st.session_state.history = []  # <-- fixed init

# -----------------------------
# Handle Quick Prompts
# -----------------------------
if "pending_prompt" in st.session_state:
    job = st.session_state.pop("pending_prompt")
    if job.get("type") == "explain":
        kw = job.get("kw", "ALERT")
        st.session_state.history.append(("user", f"Explain how {kw} tables are connected"))
        with st.spinner("Analyzing relationships..."):
            data = call_explain(schema, kw)
            time.sleep(0.15)
        st.session_state.history.append(("assistant", data))
    else:
        q = job.get("q", "")
        st.session_state.history.append(("user", q))
        with st.spinner("Thinking..."):
            data = call_chat(q, schema, tone)
            time.sleep(0.15)
        st.session_state.history.append(("assistant", data))

# -----------------------------
# Main Chat
# -----------------------------
q = st.chat_input("Ask about tables, columns, keys, partitions… (e.g., 'list tables for kyc')")
if q:
    st.session_state.history.append(("user", q))
    with st.spinner("Thinking..."):
        data = call_chat(q, schema, tone)
        time.sleep(0.15)
    st.session_state.history.append(("assistant", data))

# -----------------------------
# Render History
# -----------------------------
for role, content in st.session_state.history:
    message(role, content, typing_delay=0.0)  # set >0.0 for typewriter effect

st.divider()
st.markdown("<p class='footer'>Read-only • Dictionary views only • Parametrised queries • Shows exact SQL for audit</p>", unsafe_allow_html=True)
