# api/app.py — FastAPI entrypoint (CORS, health, /ask + routers)

from __future__ import annotations

import os
import logging
from logging.config import dictConfig
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from intents import plan_query
from db import run_query, healthcheck

# Routers (natural chat + relationship explainer)
from chat_router import router as chat_router
from explain import router as explain_router

# -----------------------------
# Logging
# -----------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

dictConfig({
    "version": 1,
    "formatters": {"json": {"()": "python_json_logger.jsonlogger.JsonFormatter"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "json", "level": LOG_LEVEL}},
    "root": {"level": LOG_LEVEL, "handlers": ["console"]},
})
logger = logging.getLogger(__name__)

# -----------------------------
# App & CORS
# -----------------------------
app = FastAPI(title="OFSAA-BOT API", version="1.0.0")

allow_origins = [o.strip() for o in os.getenv("ALLOW_ORIGINS", "*").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins or ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -----------------------------
# Schemas for /ask
# -----------------------------
class AskRequest(BaseModel):
    question: str = Field(..., min_length=1)
    schema: str = Field(..., min_length=1, max_length=64)

class AskResponse(BaseModel):
    answer: str
    tables: Optional[List[Dict[str, Any]]] = None
    sql_snippets: Optional[List[str]] = None

# -----------------------------
# Health
# -----------------------------
@app.get("/health")
async def health() -> Dict[str, Any]:
    return {"status": "ok", "db": healthcheck()}

# -----------------------------
# Deterministic /ask (NL → safe SQL, no LLM)
# -----------------------------
@app.post("/ask", response_model=AskResponse)
async def ask(req: AskRequest) -> AskResponse:
    logger.info({"event": "ask", "question": req.question, "schema": req.schema})

    plan = plan_query(req.question, req.schema)

    if os.getenv("DEMO_MODE"):
        # Mock consistent with UI demo
        mock_tables = [
            {"OWNER": req.schema, "TABLE_NAME": "TXN_ALERTS", "COMMENTS": "Alerts generated by batch (daily)"},
            {"OWNER": req.schema, "TABLE_NAME": "ALERT_HISTORY", "COMMENTS": "Alert timeline and status transitions"},
            {"OWNER": req.schema, "TABLE_NAME": "STG_PARTY_MASTER", "COMMENTS": "Staging for party/customer info"},
        ]
        return AskResponse(answer=f"(Mock) {plan.answer}", tables=mock_tables, sql_snippets=[plan.sql])

    try:
        rows = run_query(plan.sql, plan.params)
        return AskResponse(answer=plan.answer, tables=rows, sql_snippets=[plan.sql])
    except Exception as e:
        logger.exception("query_failed")
        raise HTTPException(status_code=500, detail=str(e))

# -----------------------------
# Routers
# -----------------------------
app.include_router(chat_router)     # /chat  → ML/LLM natural replies (still safe & tool-driven)
app.include_router(explain_router)  # /explain → find tables by keyword + FK graph summary

