# api/explain.py — Table discovery + relationship explainer (dictionary-only)

from __future__ import annotations
from typing import List, Dict, Any

import os
from fastapi import APIRouter
from pydantic import BaseModel

from intents import sanitize_ident
from db import run_query

router = APIRouter()

# -----------------------------
# Request / Response models
# -----------------------------
class ExplainReq(BaseModel):
    schema: str
    keyword: str  # e.g., "ALERT"

class ExplainResp(BaseModel):
    title: str
    summary: str
    tables: List[Dict[str, Any]]
    relations: List[Dict[str, Any]]  # edges: {src_table, src_cols, dst_table, dst_cols, constraint_name}
    sql_snippets: List[str]

# -----------------------------
# SQL (dictionary views only)
# -----------------------------
SQL_FIND_TABLES = (
    "SELECT c.owner, c.table_name, NVL(c.comments, '-') AS comments "
    "FROM all_tab_comments c "
    "WHERE c.owner = :owner AND UPPER(c.table_name) LIKE :kw "
    "ORDER BY c.table_name"
)

SQL_FK_EDGES = (
    "SELECT ac.constraint_name, "
    "       acc.table_name AS src_table, "
    "       LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position) AS src_cols, "
    "       r.table_name AS dst_table, "
    "       LISTAGG(rcc.column_name, ',') WITHIN GROUP (ORDER BY rcc.position) AS dst_cols "
    "FROM all_constraints ac "
    "JOIN all_cons_columns acc "
    "  ON ac.owner = acc.owner AND ac.constraint_name = acc.constraint_name "
    "JOIN all_constraints r "
    "  ON r.owner = ac.owner AND r.constraint_name = ac.r_constraint_name "
    "JOIN all_cons_columns rcc "
    "  ON r.owner = rcc.owner AND r.constraint_name = rcc.constraint_name AND rcc.position = acc.position "
    "WHERE ac.owner = :owner AND ac.constraint_type = 'R' "
    "  AND (acc.table_name IN (SELECT table_name FROM all_tab_comments WHERE owner=:owner AND UPPER(table_name) LIKE :kw) "
    "       OR r.table_name IN (SELECT table_name FROM all_tab_comments WHERE owner=:owner AND UPPER(table_name) LIKE :kw)) "
    "GROUP BY ac.constraint_name, acc.table_name, r.table_name "
    "ORDER BY acc.table_name, r.table_name"
)

SQL_PK = (
    "SELECT acc.table_name, LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position) AS pk_cols "
    "FROM all_constraints ac "
    "JOIN all_cons_columns acc "
    "  ON ac.owner=acc.owner AND ac.constraint_name=acc.constraint_name "
    "WHERE ac.owner=:owner AND ac.constraint_type='P' "
    "  AND acc.table_name IN (SELECT table_name FROM all_tab_comments WHERE owner=:owner AND UPPER(table_name) LIKE :kw) "
    "GROUP BY acc.table_name"
)

# -----------------------------
# Internal helpers
# -----------------------------
def _exec_or_mock(sql: str, params: Dict[str, Any]):
    if os.getenv("DEMO_MODE"):
        owner = params.get("owner", "OFSAAFCCM")
        if sql is SQL_FIND_TABLES:
            return [
                {"OWNER": owner, "TABLE_NAME": "TXN_ALERTS", "COMMENTS": "Alerts generated by batch (daily)"},
                {"OWNER": owner, "TABLE_NAME": "ALERT_HISTORY", "COMMENTS": "Alert timeline and status transitions"},
                {"OWNER": owner, "TABLE_NAME": "STG_PARTY_MASTER", "COMMENTS": "Staging for party/customer info"},
            ]
        if sql is SQL_FK_EDGES:
            return [
                {"CONSTRAINT_NAME": "FK_ALERTS_PARTY", "SRC_TABLE": "TXN_ALERTS", "SRC_COLS": "PARTY_ID",
                 "DST_TABLE": "STG_PARTY_MASTER", "DST_COLS": "PARTY_ID"},
                {"CONSTRAINT_NAME": "FK_HISTORY_ALERTS", "SRC_TABLE": "ALERT_HISTORY", "SRC_COLS": "ALERT_ID",
                 "DST_TABLE": "TXN_ALERTS", "DST_COLS": "ALERT_ID"},
            ]
        if sql is SQL_PK:
            return [
                {"TABLE_NAME": "TXN_ALERTS", "PK_COLS": "ALERT_ID"},
                {"TABLE_NAME": "ALERT_HISTORY", "PK_COLS": "HIST_ID"},
                {"TABLE_NAME": "STG_PARTY_MASTER", "PK_COLS": "PARTY_ID"},
            ]
    return run_query(sql, params)

def _nlg_explain(owner: str, tables: List[Dict[str, Any]], edges: List[Dict[str, Any]]) -> str:
    if not tables:
        return f"I didn’t find any tables in {owner} matching that keyword."

    # quick centrality (how many tables reference a table)
    from collections import Counter
    indeg = Counter(e["DST_TABLE"] for e in edges)
    hubs = ", ".join(f"{t} (referenced by {n})" for t, n in indeg.most_common(3)) if indeg else "none"

    lines = []
    lines.append(f"I found {len(tables)} table(s) related to your keyword. Here’s how they connect:")
    if hubs != "none":
        lines.append(f"• Hubs: {hubs}.")
    for e in edges[:12]:
        lines.append(f"• {e['SRC_TABLE']} → {e['DST_TABLE']} via ({e['SRC_COLS']}) → ({e['DST_COLS']}).")
    lines.append("\n**Table notes:**")
    for t in tables:
        lines.append(f"• {t['TABLE_NAME']} — {t.get('COMMENTS') or '-'}")
    return "\n".join(lines)

# -----------------------------
# Route
# -----------------------------
@router.post("/explain", response_model=ExplainResp)
def explain(req: ExplainReq) -> ExplainResp:
    owner = sanitize_ident(req.schema)
    kw = f"%{req.keyword.strip().upper()}%"

    tables = _exec_or_mock(SQL_FIND_TABLES, {"owner": owner, "kw": kw})
    edges  = _exec_or_mock(SQL_FK_EDGES,  {"owner": owner, "kw": kw})
    pkrows = _exec_or_mock(SQL_PK,        {"owner": owner, "kw": kw})
    pk_map = {r["TABLE_NAME"]: r["PK_COLS"] for r in pkrows}

    summary = _nlg_explain(owner, tables, edges)

    return ExplainResp(
        title=f"{req.keyword.upper()} tables in {owner}",
        summary=summary,
        tables=tables,
        relations=[
            {
                "src_table": e["SRC_TABLE"],
                "src_cols": e["SRC_COLS"],
                "dst_table": e["DST_TABLE"],
                "dst_cols": e["DST_COLS"],
                "constraint_name": e["CONSTRAINT_NAME"],
            } for e in edges
        ],
        sql_snippets=[SQL_FIND_TABLES, SQL_FK_EDGES, SQL_PK],
    )

